# Generated by Django 6.0.5 on 2026-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMapCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=10)),
                ('wagon', models.CharField(max_length=8)),
                ('dep_code', models.CharField(max_length=12)),
                ('arr_code', models.CharField(max_length=12)),
                ('journey_date', models.CharField(max_length=8)),
                ('svg', models.TextField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='trains_seat_fetched_3fe428_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'number', 'wagon', 'dep_code', 'arr_code', 'journey_date'), name='unique_seat_map_leg')],
            },
        ),
    ]
